### ISSUE TITLE
Identify

### ISSUE THREAD

**Issue by bwship** [mixpanel/mixpanel-node#13]
Hi,

Is there any  plan to integrate mixpanel.identify

https://mixpanel.com/docs/getting-started/learn-the-basics

I am trying to track an event related to another user, so I want to identify them in my code with something like this

```
mixpanel.track 'ReferralClicked'
  objectId: req.body.objectId
```

Thanks,
Bob

**Comment by mividtim** [comment]
Can I set distinct_id on a people.set call?  When I do, it seems to create no users in Mixpanel.  Is there no way to create a user, specifying the distinct_id for that user, with this library?

**Comment by mividtim** [comment]
I just found in the docs that I should be setting the $distinct_id property, not distinct_id, on people.set calls.  It would be great if the README included this property in the user-creation example.  There is really no circumstance I can think of using this Node library where you wouldn't want to specify your own.  Otherwise, how would you know what value to use on subsequent tracking calls?  You wouldn't be able to figure out the ID mixpanel created, since you have no user context.

**Comment by adelespinasse** [comment]
@mividtim Saying you need to set $distinct_id is misleading (or possibly the library has changed since you wrote that). You actually need to pass the distinct_id value as the first parameter of people.set, and other properties in the second parameter. So don't do:

```
mixpanel.people.set({
  $distinct_id: userId,
  name: name
});
```

Do this instead:
```
mixpanel.people.set(
  userId,
  { name: name }
);
```

I wish the documentation was more clear about the differences between this package and mixpanel-browser. The only place it's really clear is in the code itself:

https://github.com/mixpanel/mixpanel-node/blob/master/lib/mixpanel-node.js#L352

**Comment by mividtim** [comment]
Interesting.  I haven't tested this code in a while, but it's not throwing errors and marketing isn't complaining.  It did work with setting $distinct_id right in the properties at the time I wrote that comment, and may still work now.  I got the special property name from your documentation here:

https://mixpanel.com/help/questions/articles/special-or-reserved-properties

That's how it's documented, and it seems to work.

**Comment by adelespinasse** [comment]
Well, it didn't work for me. Maybe it would work to set $distinct_id in the properties as long as the properties were the second argument. (Unless you're using mixpanel-browser, in which case it's the first argument, as shown in most of the docs; but then you generally don't need to set $distinct_id in people.set or mixpanel.track because you can set it once with mixpanel.identify.)

I'd seen that documentation page, but it doesn't show the order of arguments for people.set (or even mention people.set), just the special property names for people records in general.

(I'm not affiliated with Mixpanel, in case that wasn't clear; just a user trying to clear up some confusion.)

**Comment by aviadbd** [comment]
I think its possible to create a method Mixpanel#identify(id) which returns an object with all the mixpanel methods, just automatically adding the id. That way it can be passed along to downward components who dont need to figure out the distinct_id by themselves. I've done something like that for my own application needs, if anyone's interested in code examples, but I think its fairly simple and better done within the API.

**Comment by andirsun** [comment]
If someone still interested, is possible to identify anonymous users on backend library. You can use track method and send an event with $identify as eventName
```
mixpanel.track('$identify',{
    $identified_id: <Use your user.id>,
    $anon_id: <Use the device_id from frontend library eg: $device:1231-12312-132>,
})
```
This will act as a regular mixpanel.identify method available on frontend library.

**Comment by shide1989** [comment]
Look at the doc at https://docs.mixpanel.com/docs/tracking-methods/sdks/nodejs#sending-events, 
you can use it server side this way: 

```javascript
const Mixpanel = require('mixpanel');
const mp = Mixpanel.init('YOUR_PROJECT_TOKEN');
 
// track "some_event" for distinct_id 12345
// with "plan" event prop
mp.track('some_event', {
    distinct_id: '12345',
    plan: 'premium'
});
```
