### ISSUE TITLE
time property should not trigger /import endpoint

### ISSUE THREAD

**Issue by jklundell** [mixpanel/mixpanel-node#38]
In a server-side implementation of the Mixpanel API, it's reasonable to want to use the client's timestamp (rather than an implicit "now") for the time property. But in the current implementation, that causes the /import endpoint to be used, with the consequence that the event doesn't appear in the Mixpanel Live View.

One alternative: add an endpoint argument to track() (so that import() can use it to force the /import endpoint) and change the time-property test to look for a timestamp older than Mixpanel's 5-day limit for /track.

**Comment by markoshust** [comment]
I think this line should just be changed:

https://github.com/mixpanel/mixpanel-node/blob/master/lib/mixpanel-node.js#L120

So that it automatically defaults to `/track` if the time is less than or equal to 5 days. If someone is sending the `track` event, they inherently do not want it to be classified as an import.
