### ISSUE TITLE
Where are all the insights like Browser, IP, Referrer, etc gone?

### ISSUE THREAD

**Issue by nottinhill** [mixpanel/mixpanel-node#56]
We all know the advanced telemetry from the FrontEnd JS implementation of MixPanel. Where is this data or can't it be tracked from via the BackEnd ?

**Comment by freeall** [comment]
You have to add it yourself. In the browser implementation Mixpanel does it automatically, but in the backend it will not know any of this.

What you could do is have your frontend pass this information to your backend, and then have the backend add this to the events.

**Comment by tdumitrescu** [comment]
Since this library isn't tied to any specific server or framework, there's no universal way to grab this information (indeed, you might not be using it in the context of a webserver at all). If you're using Express or another Connect-based server, https://www.npmjs.com/package/express-useragent will parse request headers and expose a lot of this information to your app code. Hope that helps!
