### ISSUE TITLE
Add support for mixpanel .register

### ISSUE THREAD

**Issue by adamt19** [mixpanel/mixpanel-node#60]
So that we can set super properties that pass to mixpanel on every subsequent event..

**Comment by tdumitrescu** [comment]
Hi @adamt19, since this is a server-side library which will typically be used to send events for multiple users, you'll need to keep track of superproperties in your application code, probably tied in some way to your user/session scheme. For a previous discussion see https://github.com/mixpanel/mixpanel-node/issues/48. Drop us a line at support@mixpanel.com if you need help with this, thanks!
