### ISSUE TITLE
Booleans?

### ISSUE THREAD

**Issue by evantahler** [mixpanel/mixpanel-node#63]
Say I want to pass a boolean property about a user, like `{$unsubscribed: true}` (from [here](https://mixpanel.com/help/questions/articles/how-do-i-customize-my-email-unsubscribe-link)).  

Would I Do:
a) `{$unsubscribed: true}` // boolean in JS
b) `{$unsubscribed: 'true'}` // string 'true'
C) `{$unsubscribed: 'True'}` // string 'True', as noted in the linked docs
C) `{$unsubscribed: 'TRUE'}` // string 'TRUE', as this is the only way to get the profile of the user to match the screen shot in the docs

**Comment by tdumitrescu** [comment]
I'm guessing you figured this out already since you closed the issue, but just to help anyone who lands here looking for the same info:
- in general cases, using a JS boolean is what you want
- specifically regarding the `$unsubscribed` field, you can set it to anything. From the doc you linked to: "PRO TIP: When Mixpanel disqualifies unsubscribed users from the notification pool, we specifically look for the key '$unsubscribed'. The value of '$unsubscribed' has no bearing. This means you're welcome to alter this value with confidence that the user will remain unsubscribed. One clever example might be the set the value as the date the user unsubscribed."

**Comment by evantahler** [comment]
Yup, I found it a few hours later.  Thanks for the recap!  
SEO FTW :smile:
