### ISSUE TITLE
mixpanel.get_property

### ISSUE THREAD

**Issue by ndelvalle** [mixpanel/mixpanel-node#68]
Does this library support [get_properties](https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.get_property) method?.
Example: ```mixpanel.get_property('distinct_id')```

**Comment by tdumitrescu** [comment]
`mixpanel-node` doesn't have any concept of superproperties, since its primary use case is server-side tracking where the same instance needs to handle many users simultaneously. If your application needs to maintain individual users' properties between requests, that will have to happen in your application code (probably in connection with either cookies or server-side session storage, but it depends on your app's architecture and infrastructure). Hope this helps!
